receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

exporters:
  googlecloud:
    metric:
      compression: gzip
  otlp:
    endpoint: tempo-distributed-distributor.observability.svc.cluster.local:4317
    tls:
      insecure: true  
  prometheusremotewrite:
    endpoint: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090/api/v1/write
    resource_to_telemetry_conversion:
      enabled: true
  debug:
    verbosity: detailed            

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [googlecloud, otlp, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [googlecloud, prometheusremotewrite, debug]      