apiVersion: apps/v1
kind: Deployment
metadata:
  name: otelcol
  namespace: observability
  labels:
    app.kubernetes.io/name: otelcol
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: otelcol
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: otelcol
    spec:
      serviceAccountName: otel-findy-demo
      containers:
      - image: ghcr.io/keisukesakasai/otel-findy-demo/otelcol:latest
        name: otelcol
---
apiVersion: v1
kind: Service
metadata:
  name: otelcol
  namespace: observability  
  labels:
    app.kubernetes.io/name: otelcol
spec:
  type: ClusterIP
  ports:
    - port: 4317
      targetPort: 4317
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: otelcol